// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB02vWJ3PWG9u96hAWUll_Jc2P4BNJ-n3M',
    appId: '1:553304849982:web:91bb10669781bc57d39b6f',
    messagingSenderId: '553304849982',
    projectId: 'social-hub-abad9',
    authDomain: 'social-hub-abad9.firebaseapp.com',
    storageBucket: 'social-hub-abad9.firebasestorage.app',
    measurementId: 'G-NBBEBXFWXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz8jwlZp1bEnVP8xOWuSkd78cCzfdCpr0',
    appId: '1:553304849982:android:e769af29dbfe4bf5d39b6f',
    messagingSenderId: '553304849982',
    projectId: 'social-hub-abad9',
    storageBucket: 'social-hub-abad9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3Gv3A0ZMsOcxvdbdjBRqI7PaiV8yVN_M',
    appId: '1:553304849982:ios:754ef797780bee14d39b6f',
    messagingSenderId: '553304849982',
    projectId: 'social-hub-abad9',
    storageBucket: 'social-hub-abad9.firebasestorage.app',
    iosBundleId: 'com.example.socialHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3Gv3A0ZMsOcxvdbdjBRqI7PaiV8yVN_M',
    appId: '1:553304849982:ios:754ef797780bee14d39b6f',
    messagingSenderId: '553304849982',
    projectId: 'social-hub-abad9',
    storageBucket: 'social-hub-abad9.firebasestorage.app',
    iosBundleId: 'com.example.socialHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB02vWJ3PWG9u96hAWUll_Jc2P4BNJ-n3M',
    appId: '1:553304849982:web:3be2dbd8ab1fdc25d39b6f',
    messagingSenderId: '553304849982',
    projectId: 'social-hub-abad9',
    authDomain: 'social-hub-abad9.firebaseapp.com',
    storageBucket: 'social-hub-abad9.firebasestorage.app',
    measurementId: 'G-5X0GB4G682',
  );
}
